# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
# Based on lint eslint workflow on https://github.com/nextcloud/.github

name: Lint TypeScript

on: pull_request

permissions:
  contents: read

concurrency:
  group: lint-typescript-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest-low
    permissions:
      contents: read
      pull-requests: read

    outputs:
      src: ${{ steps.changes.outputs.src}}

    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        continue-on-error: true
        with:
          filters: |
            src:
              - '.github/workflows/**'
              - 'src/**'
              - 'appinfo/info.xml'
              - 'package.json'
              - 'package-lock.json'
              - 'tsconfig.json'
              - '**.js'
              - '**.ts'
              - '**.vue'

  typecheck:
    runs-on: ubuntu-latest

    needs: changes
    if: needs.changes.outputs.src != 'false'

    name: NPM typecheck

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up node and npm ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typescript:check

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest-low
    needs: [changes, typecheck]

    name: typecheck

    steps:
      - name: Summary status
        run: if ${{ needs.changes.outputs.src != 'false' && needs.typecheck.result != 'success' }}; then exit 1; fi
